### ISSUE TITLE
Using Docker DOCs

### ISSUE THREAD

**Issue by ponciusz** [eWert-Online/OSnap#35]
Hello and thanks for this library, 
I was wondering if Docker docs are in progress?

**Comment by eWert-Online** [comment]
Hi 👋 

yes, the docs are in progress. In our company we are already using OSnap inside docker exlusively. I just need to find the time to document how we do it.

Ideally I wanted to implement the server feature (#28) to make the usage inside docker easier. This will take some more time though.

Are you interested in contributing the docs are are you just asking, because you need them to get it running? 🙂

**Comment by ponciusz** [comment]
Nice Will it support Docker on ARM? thats main reason why I am looking for alternative as backstopJS Docker is not working on M1 https://github.com/garris/BackstopJS/issues/1300

**Comment by eWert-Online** [comment]
Yes, we are also have some colleagues which have a m1 Mac and it is working fine!

**Comment by ukrutt** [comment]
@ponciusz For what it's worth, I've been able to get BackstopJS to work on an M1 Mac -- with Docker.  I did need to upgrade to Ventura / 13.2 and I'm running the latest version of Docker (4.16.2).  See https://github.com/garris/BackstopJS/issues/1300#issuecomment-1424888520 .

**Comment by eWert-Online** [comment]
I will see if I can open a draft PR soon with some basic instructions for Docker. 

Maybe that will already help you 🙂

**Comment by eWert-Online** [comment]
@ponciusz 
I have gone ahead and published a basic example of how a docker setup might be done:
https://ewert-online.github.io/OSnap/Setup/using-docker/

If you have questions or feedback, feel free to reopen this issue :)
